### ISSUE TITLE
hotfix.lua的update_func处理会有bug

### ISSUE THREAD

**Issue by linxiaolong** [jinq0123/hotfix#1]
假设一种情况，A模块要更新，新旧模块如下，会发生更新后func1和func2所引用upvalue l 是不同的，这样有隐患：
old:
local M = {}
local l = {}

function M.func1()
end
function M.func2()
 l[10] = 10
end

return M

new:
local M = {}
local l  = {}

function M.func1()
 l[10] = 10
end
function M.func2()
 l[10] = 10
end

return M

**Comment by jinq0123** [comment]
I add a test and the result is as expected. I make func1() and func2() to return l, and compare tostring(l).
